In [1]:
#Data Preprocessing

#Importing the Libraries
import numpy as np # contains mathematical functions(linear algebra)
import matplotlib.pyplot as plt #for plotting graphs
import pandas as pd # used to import and manage the dataset




In [2]:
#Importing the Dataset

dataset=pd.read_csv("../input/purchaseddata/Data.csv")   #pandas is the libray used for reading dataset and the file is the csv file
X = dataset.iloc[:,:-1].values    #X is a dataframe which will contain all independent variables(input) together
                                  #iloc -index location       #.values gives the content value of column
#we are going from 0 to -1 where -1 is the last column. As -1 represents last element -2 the second last element and so on
#:-1 will exclude the last column as we have to exclude the last column purchased because that is dependent column

Y = dataset.iloc[:,-1].values #dataframe will contain dependent(output that we need to predict) variable
#X and Y are numpy arrays
print(X)
print(Y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [3]:
#Handle Missing Values
from sklearn.impute import SimpleImputer  #it contains all the machine learning models in terms of classes and methods
                                          #impute is a class        #SimpleImputer is a class
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')   #statergy is to take the mean of the column  
imputer.fit(X[:,1:3]) #It will check for 2nd and 3rd columns  for the missing values and it will use the stratergy of men and it will fit there
#imputer is the object we created for class SimpleImputer
X[:,1:3]=imputer.transform(X[:,1:3])
print(X)
print(Y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [4]:
#Encoding Categorical Data

#1. Encode independent variable
from sklearn.compose import ColumnTransformer #for encoding
from sklearn.preprocessing import OneHotEncoder#for creating dummy variables eg.creates column for each country  
ct=ColumnTransformer(transformers=[("encoder",OneHotEncoder(),[0])],remainder="passthrough")#to convert textual data into numeric data
X=np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [5]:
#Encode dependent variable

from sklearn.preprocessing import LabelEncoder 
le=LabelEncoder()
Y=le.fit_transform(Y)
print(Y)

[0 1 0 0 1 1 0 1 0 1]


In [6]:
#Splitting the dataset into training and test set

from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=1)#randomly it will select 80% records for training and 20% for testing 
print(X_train)
print(X_test)
print(Y_train)
print(Y_test)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]
[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]
[0 1 0 0 1 1 0 1]
[0 1]


In [7]:
#Feature Scaling   Also called as Normalization process        (will try to find the euclidean distance between Age and salary and values to same scale)
from sklearn.preprocessing import StandardScaler #StandardScaler converts all values from -1 to 1
sc=StandardScaler()
X_train[:,3:]=sc.fit_transform(X_train[:,3:])
X_test[:,3:]=sc.transform(X_test[:,3:])
#now the values for age and salary column should cahnge to the values in the range from -1 to 1
print(X_train)
print(X_test)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]
[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
